### ISSUE TITLE
Negative Seek Offset in Python 3.5

### ISSUE THREAD

**Issue by SirWillae** [jcrobak/parquet-python#30]
I've used your library successfully in Python 2.7, but when I tried it on Python 3.5, I ran in to a problem.  Evidently, Python 3.5 no longer supports negative seek offsets.  When I try to open a simple file, I get the following exception:

/home/czdn2lq/local/anaconda3/lib/python3.5/site-packages/parquet/__init__.py in _get_footer_size(fo)
     61 def _get_footer_size(fo):
     62     "Readers the footer size in bytes, which is serialized as little endian"
---> 63     fo.seek(-8, 2)
     64     tup = struct.unpack("<i", fo.read(4))
     65     return tup[0]

UnsupportedOperation: can't do nonzero end-relative seeks

For now, I'll go back to using Python 2.7 so it's not a huge deal.  But I'd really like to start migrating to Python 3 (it's only been out for... 8 years, now).  :-)

Thanks,
Bill

**Comment by jcrobak** [comment]
Hi Bill,

Thanks for the report. What are you doing when you see this error? Are you reading a file using the API or the command line util?

I saw this error at one point but thought it was fixed.

**Comment by SirWillae** [comment]
Sorry about that.  I should have included the calling code in my first post.  I was trying to read a file using the API, like so:

 with open('myFile.snappy.parquet') as f:
    for row in parquet.reader(f):
        print(row)

I played around with it a little more this morning.  If I change the file mode to 'rb', it works.  But then the type of the data returned is bytes.  This isn't a huge deal because I can just cast it back to a str.

**Comment by jcrobak** [comment]
@SirWillae I'm preparing a (hopeful) fix to this as follows: 1) given a better warning when file obj isn't in binary mode. 2) Implement logical types (#23) so that binary fields containing utf-8 strings are automatically decoded.

**Comment by jcrobak** [comment]
@SirWillae I've added the two items mentioned above, if you want to give it a try and provide feedback!

**Comment by elephantjim** [comment]
@jcrobak Could you reopen this issue?  The functions _check_footer_magic_bytes, _get_footer_size, and _read_footer use negative seeks and still fail.

In python3 if I try:
```
import json, parquet
with open("somefile.parquet") as fo:
  for row in parquet.DictReader(fo):
    print(json.dumps(row))
```
I get an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.4/dist-packages/parquet/__init__.py", line 375, in DictReader
    footer = _read_footer(fo)
  File "/usr/local/lib/python3.4/dist-packages/parquet/__init__.py", line 71, in _read_footer
    footer_size = _get_footer_size(fo)
  File "/usr/local/lib/python3.4/dist-packages/parquet/__init__.py", line 63, in _get_footer_size
    fo.seek(-8, 2)
io.UnsupportedOperation: can't do nonzero end-relative seeks
```

**Comment by elephantjim** [comment]
Sorry, my mistake.  I need `open("somefile.parquet", mode="rb")`.

Could you update the README to note that in python3 the mode specification is necessary?

**Comment by jcrobak** [comment]
Good idea. I also need to do a release to pickup the changes in #33 , which should give a more intuitive error, at least.
